class I18n {
  static const supported = ['ko', 'en'];

  static const Map<String, String> _alias = {
    // 흔한 대소문자/철자 흔들림 흡수
    'loginID': 'loginId',
    'loginPW': 'loginPassword',
    'loginPwd': 'loginPassword',
    'app_title': 'appTitle',
    'mvp_account_hint': 'mvpAccountHint',
  };
  
  static String tr(String lang, String key) {
    final k = _alias[key] ?? key; // ✅ alias 먼저
    final m = _dict[lang] ?? _dict['ko']!;
    final ko = _dict['ko']!;
    return (m[k] ?? ko[k] ?? k).toString();
  }

  static String trf(String lang, String key, Map<String, String> vars) {
    var out = tr(lang, key);
    vars.forEach((k, v) => out = out.replaceAll('{$k}', v));
    return out;
  }

  // ✅ "값(하드코딩 문구/단어)"를 키로 변환해서 번역
  static String v(String lang, String raw) {
    final key = _valueKey[raw] ?? raw;
    return tr(lang, key);
  }

  // ✅ 값 포맷(혹시 필요하면)
  static String vf(String lang, String raw, Map<String, String> vars) {
    final key = _valueKey[raw] ?? raw;
    return trf(lang, key, vars);
  }

  /// -------------------------
  /// 아래 2개 맵 추가
  /// -------------------------

  static const Map<String, Map<String, String>> _dict = {
    'ko': {
      // ===== 기존 키들 유지 =====
      // 예: 'appTitle': 'Field Service MVP', ...

      // ---- PDF/리포트 라벨 ----
      'appTitle': 'Field Service MVP',
      'checklist': '체크리스트',
      'installation': '설치',
      'operation': '운영',
      'troubleshoot': '트러블슈팅',
      'selectChecklistType': '준비 유형',
      'checklistByType': '{type} 체크리스트',
      'checklistEventsByType': '{type} 행사 체크리스트',
      'exhibition':'전시',
      'demo':'데모',
      'clinical':'임상',
      'login': '로그인',
      'loginId': '아이디',
      'loginPassword': '비밀번호',
      'loginFailed': '로그인 실패. 아이디/비밀번호를 확인하세요.',
      'cancel': '취소',
      'save': '저장',
      'select': '선택',
      'edit': '편집',
      'delete': '삭제',
      'add': '추가',
      'create': '생성',
      'noItems': '항목이 없습니다.',
      'noEvents': '등록된 행사가 없습니다. 우측 상단 + 버튼으로 추가하세요.',
      'eventName': '행사명',
      'eventNameHint': '예) KDDW 부스 행사',
      'eventDate': '행사일',
      'selectEventFirst': '먼저 행사(행사명/행사일)를 선택하세요.',
      'eventTypesLabel': '유형',
      'addEvent': '행사 추가',
      'editEvent': '행사 수정',
      'eventDeleteConfirm': '{name} 행사를 삭제할까요?',
      'duplicateEventTitle': '중복 행사',
      'duplicateEventMessage': '같은 행사명/행사일이 이미 있습니다: {name}',
      'openExisting': '기존 행사 열기',
      'eventDeleted': '{name} 행사가 삭제되었습니다.',
      'undo': '되돌리기',
      'todayEvents': '오늘 행사',
      'upcomingEvents': '예정 행사',
      'pastEvents': '지난 행사',
      'checklistRecordNotFound': '행사를 찾을 수 없습니다.',
      'updatedLabel': '수정',
      'hospital': '병원',
      'serial': '시리얼',
      'contactPerson': '담당자',
      'actionDate': '조치일자',
      'reportCreatedAt': '리포트 생성',
      'modelLabel': '모델',
      'gaLabel': 'GA',
      'boardLabel': '보드',
      'symptomLabel': '현상',
      'causeLabel': '원인',
      'actionMethod': '조치방식',
      'appliedSolution': '적용 솔루션',

      // ---- 공통 ----
      'paragraphs': '문단',
      'bullets': '불릿',
      'step': '단계',
      'installGuide': '설치 가이드',
      'imageLoadFailedHint': '이미지 로드 실패 (경로/pubspec 확인)',
      'idAutoGenerated': 'id는 자동 생성됩니다. (예: {id})',

      // ---- 체크리스트 상태 ----
      'status_ok': 'O',
      'status_verifying': '검증 중',
      'status_fail': 'X',

      // ---- 체크리스트 그룹 ----
      'cg_core': '본체 및 핵심 장비',
      'cg_accessories': '액세서리 및 케이블, 전원',
      'cg_consumables': '소모품',
      'cg_promo': '홍보물',
      'cg_clean': '세척',

      // ---- (선택) 가이드 편집 힌트 예시 ----
      'hint_paragraph_example': '예) 1. ME-400/470를 카트 제일 윗칸에 배치',
      'hint_bullet_example': '예) 안정성을 위해 모든 영상 케이블은 DVI 사용 권장',

      // ---- 로그인 ----
      'mvpAccountHint': 'MVP 계정: a / a',
    },

    'en': {
      '본체 및 핵심 장비': 'Main Unit & Core Equipment',
      '액세서리 및 케이블, 전원': 'Accessories, Cables & Power',
      '소모품': 'Consumables',
      '홍보물': 'Marketing Materials',
      '세척': 'Cleaning',

      // ---- items
      '내시경 광원장치': 'Light Source Unit',
      '내시경 스코프': 'Endoscope Scope',
      '노트북+전원(타입확인)': 'Laptop + Power (check type)',
      '모니터': 'Monitor',
      '모니터 거치대': 'Monitor Mount',
      '석션펌프': 'Suction Pump',
      '시뮬레이터': 'Simulator',
      '워터젯': 'Water Jet',
      '카트': 'Cart',

      'SDI to SDI 케이블': 'SDI to SDI cable',
      'DVI to DVI 케이블': 'DVI to DVI cable',
      'HDMI to HDMI 케이블': 'HDMI to HDMI cable',
      'HDMI to DVI 케이블': 'HDMI to DVI cable',
      'HDMI to SDI 컨버터': 'HDMI to SDI converter',
      'SDI to HDMI 컨버터': 'SDI to HDMI converter',
      'HDMI to HDMI 컨버터': 'HDMI to HDMI converter',
      'DVI 스위치': 'DVI Switch',
      'DVI 스플리터': 'DVI Splitter',
      'HDMI 스위치': 'HDMI Switch',
      'HDMI 스플리터': 'HDMI Splitter',
      'HDMI 캡쳐카드': 'HDMI Capture Card',
      '업데이트 USB': 'Update USB',
      '캠링크': 'Camlink',
      'usb 허브': 'USB Hub',
      'Wifi 동글': 'Wi-Fi Dongle',
      '꽃지킴이': 'Lens Protector',
      '모니터 전원': 'Monitor Power',
      '물병': 'Water Bottle',
      '석션실린터': 'Suction Cylinder',
      '석션튜브': 'Suction Tube',
      '스피커': 'Speaker',
      '시뮬레이터 테이블': 'Simulator Table',
      '워터젯튜브+어답터': 'Water-Jet Tube + Adapter',
      '이리게이션튜브': 'Irrigation Tube',
      '키보드 및 마우스': 'Keyboard & Mouse',
      '테이블 천': 'Table Cloth',
      '풋페달': 'Foot Pedal',
      '함체/딥아이 전원': 'Main Unit / DEEPEYE Power',
      '해외 전력 어답터': 'Overseas Power Adapter',
      '화밸캡': 'White Balance Cap',
      '멀티탭': 'Power Strip',

      'P4 오링': 'P4 O-ring',
      '공구(드라이버, 렌치, 니퍼 등)': 'Tools (driver, wrench, nipper, etc.)',
      '루브리컨트': 'Lubricant',
      '물티슈': 'Wet Wipes',
      '안티포그': 'Anti-fog',
      '여분 키마 배터리': 'Spare Keyma Battery',
      '자이스': 'ZEISS',
      '장갑': 'Gloves',
      '키친타월': 'Kitchen Towels',
      '인스트루먼츠(포셉, 스네어 등)': 'Instruments (forceps, snare, etc.)',

      '가방': 'Bag',
      '메디인테크 명찰 랜야드': 'MedInTech Lanyard',
      '방명록': 'Guest Book',
      '볼펜': 'Pen',
      '본부장님 명함': 'Business Cards',
      '설문지': 'Survey Forms',
      '소프트웨어 카다로그': 'Software Catalog',
      '스테이플러': 'Stapler',
      '제품 카타로그': 'Product Catalog',

      '방수캡': 'Waterproof Cap',
      '세척기 어답터': 'Washer Adapter',
      '세척솔 롱': 'Cleaning Brush (Long)',
      '세척솔 숏': 'Cleaning Brush (Short)',
      '에어러버': 'Air Rubber',
      '푸시기 (릭테스터기)': 'Leak Tester',

      // ---- variants (옵션들도 표시용 번역)
      '전시용': 'Exhibition',
      '제품용': 'Product',
      '코켄': 'KOKEN',
      '메디컬IP': 'Medical IP',
      '고산': 'Gosan',
      '데모': 'Demo',
      '전시': 'Exhibition',
      '올림푸스': 'Olympus',
      '휴온스': 'HUONS',
      'ASAP': 'ASAP',
      '주황2': 'Orange #2',
      '주황1': 'Orange #1',
      '헤르가1': 'HERGA #1',
      '헤르가2': 'HERGA #2',
      '소형 스탠드': 'Small Stand',
      '대형 스탠드': 'Large Stand',
      '암': 'Arm',
      '수직암': 'Vertical Arm',


      // ---- PDF/리포트 라벨 ----
      'appTitle': 'Field Service MVP',
      'checklist': 'Checklist',
      'installation': 'Installation',
      'operation': 'Operation',
      'troubleshoot': 'Troubleshooting',
      'selectChecklistType': 'Check type',
      'checklistByType': '{type} checklist',
      'checklistEventsByType': '{type} event checklists',
      'exhibition':'Exhibition',
      'demo':'Demo',
      'clinical':'Clinical',
      'login': 'Login',
      'loginId': 'ID',
      'loginPassword': 'Password',
      'loginFailed': 'Login failed. Please check your ID/password.',
      'cancel': 'Cancel',
      'save': 'Save',
      'select': 'Select',
      'edit': 'Edit',
      'delete': 'Delete',
      'add': 'Add',
      'create': 'Create',
      'noItems': 'No items.',
      'noEvents': 'No events yet. Add one with the + button.',
      'eventName': 'Event name',
      'eventNameHint': 'e.g.) KDDW booth event',
      'eventDate': 'Event date',
      'selectEventFirst': 'Select event (name/date) first.',
      'eventTypesLabel': 'Types',
      'addEvent': 'Add event',
      'editEvent': 'Edit event',
      'eventDeleteConfirm': 'Delete event "{name}"?',
      'duplicateEventTitle': 'Duplicate event',
      'duplicateEventMessage': 'An event with the same name/date already exists: {name}',
      'openExisting': 'Open existing',
      'eventDeleted': 'Deleted event: {name}',
      'undo': 'Undo',
      'todayEvents': 'Today',
      'upcomingEvents': 'Upcoming',
      'pastEvents': 'Past',
      'checklistRecordNotFound': 'Checklist event not found.',
      'updatedLabel': 'Updated',
      'hospital': 'Hospital',
      'serial': 'Serial',
      'contactPerson': 'Contact',
      'actionDate': 'Action date',
      'reportCreatedAt': 'Report created',
      'modelLabel': 'Model',
      'gaLabel': 'GA',
      'boardLabel': 'Board',
      'symptomLabel': 'Symptom',
      'causeLabel': 'Cause',
      'actionMethod': 'Action',
      'appliedSolution': 'Applied solution',

      // ---- 공통 ----
      'paragraphs': 'Paragraphs',
      'bullets': 'Bullets',
      'step': 'Step',
      'installGuide': 'Installation Guide',
      'imageLoadFailedHint': 'Failed to load image (check path/pubspec)',
      'idAutoGenerated': 'ID is auto-generated. (e.g., {id})',

      // ---- 체크리스트 상태 ----
      'status_ok': 'O',
      'status_verifying': 'Verifying',
      'status_fail': 'X',

      // ---- 체크리스트 그룹 ----
      'cg_core': 'Main Unit & Core Devices',
      'cg_accessories': 'Accessories, Cables & Power',
      'cg_consumables': 'Consumables',
      'cg_promo': 'Promotional Materials',
      'cg_clean': 'reprocessing',

      // ---- (선택) 가이드 편집 힌트 예시 ----
      'hint_paragraph_example': 'e.g.) 1. Place ME-400/470 on the top shelf of the cart',
      'hint_bullet_example': 'e.g.) For stability, recommend using DVI for all video cables',

      // ---- 로그인 ----
      'mvpAccountHint': 'MVP account: a / a',
    },
  };

  /// ✅ "하드코딩 값" -> i18n 키
  static const Map<String, String> _valueKey = {
    // 체크리스트 그룹 (raw -> key)
    '본체 및 핵심 장비': 'cg_core',
    '액세서리 및 케이블, 전원': 'cg_accessories',
    '소모품': 'cg_consumables',
    '홍보물': 'cg_promo',
    '세척': 'cg_clean',

    // 상태값(혹시 raw로 쓰는 경우)
    '검증 중': 'status_verifying',

    // 편집 UI 라벨/힌트(raw -> key)
    'Paragraphs': 'paragraphs',
    'Bullets': 'bullets',
    '예) 1. ME-400/470를 카트 제일 윗칸에 배치': 'hint_paragraph_example',
    '예) 안정성을 위해 모든 영상 케이블은 DVI 사용 권장': 'hint_bullet_example',

    // 기타 raw
    '설치 가이드': 'installGuide',
  };
}
