import 'translations_en.dart';
import 'translations_ko.dart';

class I18n {
  static const supported = ['ko', 'en'];

  static const Map<String, String> _alias = {
    // 흔한 대소문자/철자 흔들림 흡수
    'loginID': 'loginId',
    'loginPW': 'loginPassword',
    'loginPwd': 'loginPassword',
    'app_title': 'appTitle',
    'mvp_account_hint': 'mvpAccountHint',
  };
  
  static String tr(String lang, String key) {
    final k = _alias[key] ?? key; // ✅ alias 먼저
    final m = _dict[lang] ?? _dict['ko']!;
    final ko = _dict['ko']!;
    return (m[k] ?? ko[k] ?? k).toString();
  }

  static String trf(String lang, String key, Map<String, String> vars) {
    var out = tr(lang, key);
    vars.forEach((k, v) => out = out.replaceAll('{$k}', v));
    return out;
  }

  // ✅ "값(하드코딩 문구/단어)"를 키로 변환해서 번역
  static String v(String lang, String raw) {
    final key = _valueKey[raw];
    return key == null ? raw : tr(lang, key);
  }

  // ✅ 값 포맷(혹시 필요하면)
  static String vf(String lang, String raw, Map<String, String> vars) {
    final key = _valueKey[raw];
    return key == null ? raw : trf(lang, key, vars);
  }

  /// -------------------------
  /// 아래 2개 맵 추가
  /// -------------------------

  static const Map<String, Map<String, String>> _dict = {
    'ko': {
      // ===== 기존 키들 유지 =====
      // 예: 'appTitle': 'Field Service MVP', ...

      // ---- PDF/리포트 라벨 ----
      'appTitle': 'Field Service MVP',
      'login': '로그인',
      'loginId': '아이디',
      'loginPassword': '비밀번호',
      'loginFailed': '로그인 실패. 아이디/비밀번호를 확인하세요.',
      'cancel': '취소',
      'save': '저장',
      'select': '선택',
      'edit': '편집',
      'delete': '삭제',
      'add': '추가',
      'hospital': '병원',
      'serial': '시리얼',
      'contactPerson': '담당자',
      'actionDate': '조치일자',
      'reportCreatedAt': '리포트 생성',
      'modelLabel': '모델',
      'gaLabel': 'GA',
      'boardLabel': '보드',
      'symptomLabel': '현상',
      'causeLabel': '원인',
      'actionMethod': '조치방식',
      'appliedSolution': '적용 솔루션',

      // ---- 공통 ----
      'paragraphs': '문단',
      'bullets': '불릿',
      'step': '단계',
      'installGuide': '설치 가이드',
      'imageLoadFailedHint': '이미지 로드 실패 (경로/pubspec 확인)',
      'idAutoGenerated': 'id는 자동 생성됩니다. (예: {id})',

      // ---- 체크리스트 상태 ----
      'status_ok': 'O',
      'status_verifying': '검증 중',
      'status_fail': 'X',

      // ---- 체크리스트 그룹 ----
      'cg_core': '본체 및 핵심 장비',
      'cg_accessories': '액세서리 및 케이블, 전원',
      'cg_consumables': '소모품',
      'cg_promo': '홍보물',
      'cg_clean': '세척',

      // ---- (선택) 가이드 편집 힌트 예시 ----
      'hint_paragraph_example': '예) 1. ME-400/470를 카트 제일 윗칸에 배치',
      'hint_bullet_example': '예) 안정성을 위해 모든 영상 케이블은 DVI 사용 권장',

      // ---- 로그인 ----
      'mvpAccountHint': 'MVP 계정: a / a',
    },

    'en': {
      // ===== 기존 키들 유지 =====

      // ---- PDF/리포트 라벨 ----
      'appTitle': 'Field Service MVP',
      'login': 'Login',
      'loginId': 'ID',
      'loginPassword': 'Password',
      'loginFailed': 'Login failed. Please check your ID/password.',
      'cancel': 'Cancel',
      'save': 'Save',
      'select': 'Select',
      'edit': 'Edit',
      'delete': 'Delete',
      'add': 'Add',
      'hospital': 'Hospital',
      'serial': 'Serial',
      'contactPerson': 'Contact',
      'actionDate': 'Action date',
      'reportCreatedAt': 'Report created',
      'modelLabel': 'Model',
      'gaLabel': 'GA',
      'boardLabel': 'Board',
      'symptomLabel': 'Symptom',
      'causeLabel': 'Cause',
      'actionMethod': 'Action',
      'appliedSolution': 'Applied solution',

      // ---- 공통 ----
      'paragraphs': 'Paragraphs',
      'bullets': 'Bullets',
      'step': 'Step',
      'installGuide': 'Installation Guide',
      'imageLoadFailedHint': 'Failed to load image (check path/pubspec)',
      'idAutoGenerated': 'ID is auto-generated. (e.g., {id})',

      // ---- 체크리스트 상태 ----
      'status_ok': 'O',
      'status_verifying': 'Verifying',
      'status_fail': 'X',

      // ---- 체크리스트 그룹 ----
      'cg_core': 'Main Unit & Core Devices',
      'cg_accessories': 'Accessories, Cables & Power',
      'cg_consumables': 'Consumables',
      'cg_promo': 'Promotional Materials',
      'cg_clean': 'reprocessing',

      // ---- (선택) 가이드 편집 힌트 예시 ----
      'hint_paragraph_example': 'e.g.) 1. Place ME-400/470 on the top shelf of the cart',
      'hint_bullet_example': 'e.g.) For stability, recommend using DVI for all video cables',

      // ---- 로그인 ----
      'mvpAccountHint': 'MVP account: a / a',
    },
  };

  /// ✅ "하드코딩 값" -> i18n 키
  static const Map<String, String> _valueKey = {
    // 체크리스트 그룹 (raw -> key)
    '본체 및 핵심 장비': 'cg_core',
    '액세서리 및 케이블, 전원': 'cg_accessories',
    '소모품': 'cg_consumables',
    '홍보물': 'cg_promo',
    '세척': 'cg_clean',

    // 상태값(혹시 raw로 쓰는 경우)
    '검증 중': 'status_verifying',

    // 편집 UI 라벨/힌트(raw -> key)
    'Paragraphs': 'paragraphs',
    'Bullets': 'bullets',
    '예) 1. ME-400/470를 카트 제일 윗칸에 배치': 'hint_paragraph_example',
    '예) 안정성을 위해 모든 영상 케이블은 DVI 사용 권장': 'hint_bullet_example',

    // 기타 raw
    '설치 가이드': 'installGuide',
  };
}
